PULP_APP = dotprod
PULP_APP_FC_SRCS = main.c
PULP_APP_CL_SRCS = cluster.c

PULP_LDFLAGS += -lplpdsp -lm

PULP_CFLAGS += -O3 -g -DRTOS_PMSIS -DARCHI_CORE_HAS_PULPV2

-include $(RULES_DIR)/pmsis_rules.mk