# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: publish-docs
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: docs/
    - name: Generate Doxygen Documentation
      run: |
        mkdir doxybook2; cd doxybook2
        wget https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip
        unzip doxybook2-linux-amd64-v1.4.0.zip; cd ../
        chmod +x doxybook2/bin/doxybook2
        mkdir docs/refmanual
        ./doxybook2/bin/doxybook2 --input docs/xml --output docs/refmanual --config docs/doxybook2.json
        rm -rf doxybook2
    - run: pip install -r docs/requirements.txt
    - run: mkdocs gh-deploy --force
